### ISSUE TITLE
link between location and waterbody table

### ISSUE THREAD

**Issue by andersfi** [NINAnor/NOFA#12]
# No link between waterbody table and location table
A lot of ID fields floating around in the different tables ("waterBodyID" in location table, "id" in the waterbody table). At the moment, there is no simple one-to-many key between the waterbody table and the location table. I guess this is partly because in some instances the fennoscandian lake table (temporary.lakes_nosefi ) several waterbodies can reefer the same "whole-watebody-location" (e.g. locationType: waterbody centroid). I guess however that this is fixed in the current nofa.waterbody / nofa.lake table (holding only Norwegian lakes)? Should probably open up a new issue / enhancement for importing the SE and FI lake polygons..

Link these **location types**:
- [x] link `lake outlet` and `lake centroid`
- [ ] 'other waterBody'
- [ ] 'samplingPoint lake'
- [ ] 'samplingPoint stream'
- [ ] 'transect'

**Comment by JakobMiksch** [comment]
Now, it already [works](https://github.com/NINAnor/invafish/commit/75c4e7d43dfad16e86343864558952f2db2deb16). But we can still refine the "algorithm" This should not be too hard anymore, because we have the basic skeleton already ... Bascially we have to decide under which conditions we want to match lakes and we have to decide which matching_remarks we shall write ...

**Comment by ninsbl** [comment]
Can we close this?

**Comment by JakobMiksch** [comment]
The basic functionality works. But like written in my comment above, we can still discuss if the matching method actually makes sense. 
Moreover, the function in NOFA uses `ORDER BY ST_Distance(location.geom, lake.geom)` which could be replaced by `location.geom <-> lake.geom`. But this can only be done if we upgrade NOFA to the latest PostGIS version (#32).

**Comment by ninsbl** [comment]
The core of this issue is duplicating  #36 and #31
The latter is closed as invalid, so only improving the matching remains....
