### ISSUE TITLE
Count of lakes with fish observation per county

### ISSUE THREAD

**Issue by bufferclip** [NINAnor/NOFA#19]
We got a user request to extract data about fish observations:

We shall count the lakes which have at least one occurrence of a fish species.

**Comment by mdlux** [comment]
The query should count:
how many lakes in each county have at least one occurrence for each of 3 species:
Phoxinus phoxinus
Rutilus rutilus
Esox Lucius
We should also divide the results according to 3 population trend criteria:
introduced
native
unknown

**Comment by bufferclip** [comment]
Useful ressources:
https://youtu.be/6yTFkLMOY_s?t=3m2s

**Comment by bufferclip** [comment]
https://gis.stackexchange.com/questions/54661/count-points-in-polygon-with-postgis
https://youtu.be/6yTFkLMOY_s?t=3m2s

**Comment by bufferclip** [comment]
That are our IDs:

'Rutilus rutilus',26134
'Esox lucius',26181
'Phoxinus phoxinus',26138

**Comment by andersfi** [comment]
No need to invoke spatial queries. Just summarize on county, species and establismentMeans from  nofa.view_occurrence_all. 

Warning: nofa is not up to date. Need to run batc_add* etc first.

**Comment by andersfi** [comment]
sorry, I meant nofa.view_aggregated_occurrence

**Comment by andersfi** [comment]
see https://github.com/NINAnor/invafish/blob/master/R_markdown_reports/get_populations_county.rmd
Currently reading from nofa_sandbox
closing issue

**Comment by mdlux** [comment]
Solved by Anders
