### ISSUE TITLE
bibliographicCitation

### ISSUE THREAD

**Issue by andersfi** [NINAnor/NOFA#2]
The term dwc:bibliographicCitation (http://rs.tdwg.org/dwc/terms/#dcterms:bibliographicCitation) is intended used as "a statement indicating how this record should be cited (attributed) when used." This field does not belong in the m_dataset as now since there are a lot of datasets containing citations/references linked to individual events (e.g.  literature surveys). The citation of the dataset itself could be 

Example: In the sandbox, the dataset AUREDATABASEN_OlaUgedal_NINA is assigned multiple datasetIDs and multipel bibliographic citations. Presumably, this is done to add citations to data sources for individual events/occurrences. 

Ideally, one would like each citation / reference in the m_reference table. However, unless some clever solution comes up, there may be a lot of work pulling in references and structuring them when the original source. 

Suggestion 1: move biblographicCitation to the m_refference table and use refferenceID as link. Possibly autocompleate bibliographicCitation from terms in m_refference table if not filled in by user (as in the case with AUREDATABASEN. (the m_refference table needs some serious cleaning up also, but that's a different story). 
Suggestion 2: move bibliographicCitation to the event tabel

**Comment by andersfi** [comment]
Some browsing around. bibliographicCitation is used for record level citation, i.e. in case the citation of an individual record is having a different citation than the dataset. see e.g. [OBIS manual](http://www.iobis.org/manual/darwincore/#sampling). Suggest that we  move bibliographic citation to refference tabel, and rename the field in the m_dataset to correspond to "citation", which is from the EML metadata standard. This has no implications for basic usage of data, but will have for pluggins etc.

**Comment by andersfi** [comment]
We should start using the term [associatedReferences](http://tdwg.github.io/dwc/terms/index.htm#associatedReferences) in the event table. bibliographicCitation can stand as it is for now in the m_refference table?

**Comment by ninsbl** [comment]
bibliographicCitation is a term for m_dataset (how the dataset could be cited)
associatedReferences in event and links to one or more references in m_reference
Use updated m_reference table (in temporary schema)

**Comment by ninsbl** [comment]
m_refrence overhaul:

1. Replace "referenceTypeID" with "referenceType" and thus change also PKEY in "l_referenceType"
2. Rename "endret_av" to "modifiedBy"
3. Remove "tempID"

Columns:

- referansetype text COLLATE pg_catalog."default",
- beskrivelse text COLLATE pg_catalog."default",
- "referanseType" text COLLATE pg_catalog."default",
- description text COLLATE pg_catalog."default",
- year_temp double precision

seem to be remnants from the update process / a join of l_referenceType. Assuming they should not be transfered to m_reference!?!

Is it OK to also remove "ownerInstitutionCode" and "dataOwner" as they are
1. empty and
2. data ownership and access rights are handled in m_dataset...

**Comment by andersfi** [comment]
Thanks, this will work!

**Comment by ninsbl** [comment]
Since m:n relations in PostgreSQL should be modeled with a "join table" (see: http://dba.stackexchange.com/questions/60132/foreign-key-constraint-on-array-member)

We stick to a 1:n relation between references in m_reference and "associatedReferences" in the event table, because cases where one event is linked to more references the most likely very very rare.

Code for a join table implementation can be found here:
https://github.com/NINAnor/invafish/blob/master/nofa/fix_bibliographicCitation.sh
if we find out that we want to have a m:n relation...
