### ISSUE TITLE
run pgAdmin4 as web application on server

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFA#25]
[pgAdmin4 ](https://www.pgadmin.org/) can be run as web application on the [server](https://www.pgadmin.org/docs/pgadmin4/dev/server_deployment.html). It more or less behaves like an desktop program then. This means that the users (we) could access the database via the browser without installing anything. 

I have used pgAdmin4 in the browser on Ubuntu already and I find it nice and stable. (The version on Windows is a bit buggy - it's not updated either). Moreover I like the clean user interface of pgAdmin4. 

However, the installation should be done by someone who is aware of IT security ...

**Comment by ninsbl** [comment]
Benefits don't justify security risks
