### ISSUE TITLE
Simplify views

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFA#27]
We could simplify the species specific views with something like this:

```SQL
CREATE OR REPLACE VIEW nofa.view_occurrence_pike AS

    SELECT    * 
      FROM     nofa.view_occurrence_all
    WHERE     l_taxon."scientificName" = 'Esox lucius';
```

**Comment by andersfi** [comment]
Ah.. thank you! Good idea  - It only makes me sad that I didn't think that far myself (=

**Comment by JakobMiksch** [comment]
The suggested approach does not work in Postgres.
