### ISSUE TITLE
organismQuantityID / organismQuantityMetric

### ISSUE THREAD

**Issue by andersfi** [NINAnor/NOFA#3]
The occurrence table holds currently the two columns "organismQuantityID" / "organismQuantityMetric" which referees to the l_organismQuantityType table. Several issues with this that goes both on database structure and use of field names. 

**Attempt of structuring issues:**
i) Firstly, it's slightly confusing and inconvenient to go through this lookup-table in order to get to the DwC fields organismQuantity and organismQuantityType. Replace the terms in the occurrence table with the propper DwC terms and move values there. There should still be a lookup table for organismQuanityType.  
ii) the organismQuantityType NOFA stockStatus belongs in the ocurrenceStatus field where the [GBIF controlled vocabulary for occurrenceStatus](http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml) should be re-used. That corresponds with the NOFA StockStatus as follows: abundant=common, normal=rare, sparse=irregular. Alternatively, abundant and normal should be coerced together to norma and orgininal information retained in MoF table, however the first solution is conservative and can always be re-done. 
iii) The NOFA stockChange scale does not really belong in the organism quantity field. This correspond to the [IUCN red list term "population trend"](http://www.iucnredlist.org/initiatives/mammals/description/glossary), which the terms "increasing; decreasing; stable; and unknown" that directly translate to the main stockChange, with exception of extinct or introduced, but which sort of falls on each side of this nominal scale. 

**Suggest:** change field names in occurrence table organismQuantity and organismQuantityType with a lookup table following the [GBIF controlled vocabulary for organismQuantityType](http://rs.gbif.org/vocabulary/gbif/quantity_type_2015-07-10.xml). Move information on NOFA stockStatus to occurrenceStatus, and create new field populationTrend reffering to the IUCN term.

**Comment by andersfi** [comment]
i) add common, rare and irregular to the l_occurrenceStatus table holding the controlled vocabulary for occurrenceStatus
ii) adding a table l_populationTrend for holding the controlled vocabulary for populationTrend

**Comment by mdlux** [comment]
Agree, naming convention should follow more the DwC guidelines. who's assigned to that?

**Comment by mdlux** [comment]
I removed myself from assignement. I think Anders or Stefan are more reliable for DB level changes. Or, we can discuss it better before I do it, if you ask me to.

**Comment by andersfi** [comment]
changed accordingly

**Comment by mdlux** [comment]
Probably is a good idea to harmonize the db structure. 
The table l_occurrenceStatus has no ID column, and the occurrenceStatus column (text) is used as a primary key.
The table l_populationTrend instead has an integer ID column.
Why such differences? Reopening the issue.

**Comment by mdlux** [comment]
And to include some best practices:
primary key should be short, numeric and immutable. So the l_populationTrend way is better, in my opinion. See also:
http://stackoverflow.com/questions/337503/whats-the-best-practice-for-primary-keys-in-tables

**Comment by andersfi** [comment]
Well spotter!

Actually, it's worse. The l_populationTrend table has an integer ID 
column as PK, but the populationTrend term is uses as link to foreign 
key. Guess this this was done in confusion before discovering that one 
could use match simple to allow NULL values in foreign key columns, and 
hence, NULL was used in the populationTrend column of l_populationTrend 
with the result that this not could be set as PK. (PS: populationTrend 
is a typically field where we would like to allow null values as this 
field does not apply for all datatypes).

**Comment by andersfi** [comment]
Sure,  I guess there is no reason to not have a integer primary key on 
lookup tables, even though the FK constraints comes from different columns.

**Comment by mdlux** [comment]
This is why primary/foreign keys should never be from/to content columns, but from/to ID columns. This is why they should be immutable. In case NULL value are required, the solution is to simply have one record for that (example: ID 0 = NULL content). Hope being clear

**Comment by andersfi** [comment]
uh.. yes, we have to look into this. There was a reason for not doing it 
this way, have to recall.

**Comment by ninsbl** [comment]
What I got out of the discussions Matteo linked to is:
Natural keys like e.g. country code are recommended - where applicable of course - for e.g. small lookup tables, which are not regularly changed. If artificial keys are used in such tables, a UNIQUE constraint should be set also on the natural keys...  
Artificial keys (e.g. a serial) are recommended for larger tables, that are updated / added to frequently, and of course where no "natural keys" are available.
Thus, I would say, using a natural key in the l_..... tables should be quite OK. For the primary tables and m_........ tables an "artifical key" should be used...

**Comment by andersfi** [comment]
Thanks Stefan,

The l_ tables are rather small and not frequently updated (all? - have 
to check) natural keys (i.e. controlled vocabularies, such as taxonID or 
occurrenceStatus).

**Comment by mdlux** [comment]
Yes, Stefan, you are right. I was already thinking about natural keys, and cases when they are more suitable. And probably you are right, for such small tables they are better. And the second answer, suggesting to evaluate from case to case, is probably the best.

**Comment by mdlux** [comment]
l_organismQuantityType should also change, I think, keeping only rows 13, 14 and 15, right? Nofa StochChange went to populationTrend, and NOFA StockStatus to occurrenceStatus

**Comment by andersfi** [comment]
Yes, thats right. I suggest reusing the GBIF controlled vocabulary for 
this http://rs.gbif.org/vocabulary/gbif/quantity_type_2015-07-10.xml . 
Even though I think it's not that intuitive), at least it's an attempt 
to provide an standard for this field.

**Comment by ninsbl** [comment]
The taxonID in l_taxon is a bit different probably from the other "l_..." tables, as we know that species names can change (even if that does not happen all the time), the same applies probably also to ecotypeID. So in these two cases I would use an artificial key (like we do at the moment). Might be worth to have unique constraint on the names (in combination with e.g. a deprecation date column for species that got partly renamed). If we want to use species names in applications like the QGIS plugin we need to have unique names...
