### ISSUE TITLE
Update NOFA to latest PostGIS version

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFA#32]
The current version of PostGIS in NOFA is outdated. In order to use the `<->` operator, we need to update the PostGIS verison.

**Comment by ninsbl** [comment]
Updated NOFA to PostGIS 2.3.2.
Please check if everything works...

**Comment by JakobMiksch** [comment]
Thanks. I see that is has been updated. Now, I can actually launch some functions on the productive NOFA db.

@ninsbl Which command did you use for updating PostGIS?

**Comment by ninsbl** [comment]
To make it simple I used:
`ALTER EXTENSION postgis UPDATE TO "2.3.2";`

Yet, that means we are still on PG 9.5....
