### ISSUE TITLE
2 occurrences without Event

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFA#33]
I discovered that there are 2 occurrences without an event. You can find them using this query:

```
SELECT * FROM nofa.occurrence
WHERE "eventID" IS NULL
```

We might need a constraint that every occurrence MUST reference to an event. 

related: #38

**Comment by andersfi** [comment]
Delete those occurrences...

**Comment by JakobMiksch** [comment]
I deleted them using:

```
DELETE FROM nofa.occurrence
WHERE "eventID" IS NULL
RETURNING *;
```
