### ISSUE TITLE
event."locationID" and occurrence."eventID" NOT NULL

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFA#38]
So far event."locationID" and occurrence."eventID" can be NULL 

Do we want that?

Do we want occurrences WITHOUT event?

Do we want events WITHOUT locations?

related: #33

**Comment by andersfi** [comment]
Woops. I see that constraint occurrence_fk_eventID is match simple, this should probably be match full? Please change accordingly. 

event_fk_locationID is match full, this should be ok?

**Comment by JakobMiksch** [comment]
I already asked something about MATCH FULL here #39 .

@andersfi  would MATCH FULL prevent having occurrences without event?

**Comment by ninsbl** [comment]
We definately do not want an event without location and no occurrences without event.
I think whats needed is simply a NOT NULL constraint. on the referencing columns. The reason we did not have apply it is that the original database had lots of events without location. I think Anders deleted those (while Jakob recently deleted the occurrences without events) and it now should be technically possible and correct / advisable to apply the NOT NULL constraints...

**Comment by JakobMiksch** [comment]
We also have 4 events without location:

```
SELECT * FROM nofa.event
WHERE "locationID" IS NULL
```

@andersfi @ninsbl what shall we do with those 4 events?

After we have solved this we can apply:

```
ALTER TABLE nofa.occurrence ALTER COLUMN "eventID" SET NOT NULL;

ALTER TABLE nofa.event ALTER COLUMN "locationID" SET NOT NULL;
```

**Comment by andersfi** [comment]
Manually going through the notes for the events without location (luckily this was one of the few datasets where we have a fieldNumber refering to the orginal field forms....), and setting locationID for those. 
Thereafter running ALTER TABLE ..... SET NOT NULL; 

closing issue

**Comment by ninsbl** [comment]
Sorry, I was maybe a bit fast I am afraid...

parentEvents will not have a location, if remember correctly. So, we should probably discuss this @andersfi ...

**Comment by andersfi** [comment]
Well, parentEvent's can have a location, e.g. referring to an survey of a given geographic area. However, in practice they don't as this information is rarely bothered recorded. We have beaten the system by giving parentEvents without a location the locationID:"3e4ab480-7c6c-4de3-a0ca-0052b695d2a2" with locationType:"dummy".

**Comment by andersfi** [comment]
I'm sort of happy with this solution, as it's very nice to get thrown back an error when you misses the locationID.

**Comment by ninsbl** [comment]
All fine! Was not aware of that!
