### ISSUE TITLE
Do we need MATCH FULL?

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFA#39]
For our constraints we sometimes use `MATCH SIMPLE` (default) and sometimes `MATCH FULL`. According to [this](https://dba.stackexchange.com/a/71508),   `MATCH FULL` is only necessary in case of "multicolumn foreign keys". 

My question:
Do we actually need  `MATCH FULL` constraints or would  `MATCH SIMPLE` also be enough?

Related: #38

**Comment by andersfi** [comment]
Ah.. sure. No, not unless we have multicolumn constraints, which I don't think we have. But, does it matter, besides looking foolish? 
A.

**Comment by JakobMiksch** [comment]
I don't know right now - but I guess it is better to only use the settings that we actually need. Otherwise we might later on face some issues that we do not expect yet ...

**Comment by ninsbl** [comment]
I would say conclusion is that we stick to MATCH SIMPLE. Please reopen if anyone sees a good reason for using MATCH FULL.
