### ISSUE TITLE
l_taxon should be revised

### ISSUE THREAD

**Issue by andersfi** [NINAnor/NOFA#5]
Revise l_taxon to include a complete list of higher taxa ranking and taxonRank for all entries

**Comment by andersfi** [comment]
I have resolved the NOFA taxonomy table (l_taxon) against GBIF taxonomic backbone and added the ouptut to the temporary shcema in NOFA as "resolved_l_taxon" This also include higher taxa. The GBIF_key and GBIF_parentKey is linkage between higher and lower taxa. I have not done the same with the ADB taxonID (from artskart) as long as I don't know how stable they are.

**Comment by andersfi** [comment]
updated l_taxon is out  or review in the temporary schema

**Comment by ninsbl** [comment]
Just committed a script that UPSERTs eventual changes from that temporary table. If you are planning to update/synchronize the taxon list on a regularly basis, the scripts for resolving and UPSERTing should be merged!
Leaving the issue open until we have a final solution in NOFA.

**Comment by andersfi** [comment]
I have been banging my head against the resolving issue for some time now. It was harder than I though, partly because I use the GBIF API for the task, and the representation of "Artsnavnebasen" on GBIF has some issues. 

Well, "new" table out now. Main difference is more complete higher taxonomy, and inclusion of key and nubKey columns that are the GBIF keys for the species. These will resolve to a landing page of the taxon as represented for a given dataset with http://www.gbif.org/species/"key" and the GBIF backbone taxonomy landing page of the taxon with http://www.gbif.org/species/"nubKey".  These also makes it easy to retrieve data from the GBIF API directly (not tested). Also, the datasetKey is included, which is the dataset from which the taxon information is taken; resolves with http://www.gbif.org/dataset/"datasetKey". Look at it more tomorow....

**Comment by andersfi** [comment]
uh, by the way. The new l_taxon table is in the temporary shcema and called revised2_l_taxon

**Comment by ninsbl** [comment]
OK, good.
No problem to update, I just have some quick questions regarding the differences between 1. and 2. revision:

There is a "scientificName.y" column in  revised2_l_taxon. I guess it is a remnant from your R script, so I disregard it ...

The following columns are new compared to l_taxon:

-   "nameType" text COLLATE pg_catalog."default"
-   "taxonomicStatus" text COLLATE pg_catalog."default"
-   "nubKey" integer
-   "doesResolve" text COLLATE pg_catalog."default"
-   "resolved_taxonID" text COLLATE pg_catalog."default"
-   "publishedIn" text COLLATE pg_catalog."default"

Are the following

-   key integer
-   parent text COLLATE pg_catalog."default"
-   "datasetKey" text COLLATE pg_catalog."default"

 equal to

-  "GBIF_key" integer
-  "GBIF_parentKey" integer
-  "GBIF_datasetKey" text COLLATE pg_catalog."default"

And do you prefer the new naming or should we keep the "GBIF_" prefix?

The columns:

-  "dataset_taxonID" integer
-  "resolved_canonicalName" text COLLATE pg_catalog."default"

were removed compared to the first revision. Was that on purpose?

The authorship column maps to the DwC term "scientificNameAuthorship" which is already in l_taxon, right?

**Comment by ninsbl** [comment]
Fixed as described above. Closing this and opening a new ticket for future syncronisation of NOFA taxon list with GBIF / Artsdatabanken.
