### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hanna-kaisalakka** [NINAnor/NOFA#7]
It takes too much time to read three webpages to get information out of these license codes. Can we put some short explanations for the licence codes to the documentation page?

License documentation e.g.
CC0 = No Copyright
You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.

CC-BY = Mention the author
You can copy, distribute, display, and perform publicly, including to create derivative works, as long as the name of the author or copyright holder properly acknowledged. 

NLOD = Norwegian licence for open government data
This licence grants you the right to copy, use and distribute information. It does not address access to information or terms of delivery.

**Comment by andersfi** [comment]
added post on wiki with data access rights & license
