### ISSUE TITLE
Dropping the occurrence_check constraint

### ISSUE THREAD

**Issue by mdlux** [NINAnor/NOFA#8]
Assuming that OrganismQuantityID is optional, and considering future changes in namespaces, I drop the constraint (in nofa_sandbox):

CONSTRAINT occurrence_check CHECK ("substring"("organismQuantity"::text, 0, 11) = 'NOFA stock'::text AND "organismQuantityType" IS NULL OR "substring"("organismQuantity"::text, 0, 11) = 'Total mass'::text AND "organismQuantityType" IS NOT NULL)
)

with:

ALTER TABLE nofa.occurrence DROP CONSTRAINT occurrence_check;

**Comment by ninsbl** [comment]
I cannot see any problem with that, so go ahead and delete. But I don`t know how and to what extent the other changes on DB level were made...
Is there any code around that documented the related changes?
Could not find anything on github...

**Comment by andersfi** [comment]
I have a feeling that this was related to the structure and solution around the former l_organismQuantity table, with multiple concepts in one field (which we have moved / are moving away from). In that case it's redundant - so yes - delete please.

**Comment by andersfi** [comment]
occurrence_check contraint dropped.
