### ISSUE TITLE
add lookup tables for replacing organismQuantityID

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/NOFA#9]
Now hardcoded in the plugin the drop down list should be flled from DB

**Comment by ninsbl** [comment]
See:
nofa."l_populationTrend"
and 
nofa."l_occurrenceStatus"

**Comment by andersfi** [comment]
created new l_organismQuantiyType with organismQuantityType as primary key (natural key) using GBIF controlled vocabulary. 

closing issue.
